CC=gcc --std=c99 -g

all: part2 part3 part4

part2: part2.c
	$(CC) part2.c -o part2

part3: part3.c
	$(CC) part3.c -o part3

part4: part4.c
	$(CC) part4.c -o part4

clean:
	rm -f *.o part2 part3 part4
